---

- name: provision dtool-lookup-server
  hosts: all

  vars_files:
    - vars.yml

  roles:

    - epel
    - ntp
    - mongodb
    - python_tools
    - nginx 
    - firewalld
    - dtool_lookup_server
