---

- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /opt/get_pip.py
  register: get_pip_downloaded

- name: install pip
  command: python /opt/get_pip.py
  when: get_pip_downloaded is changed
